/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_HX8394D_OTOTZ60_720P_VIDEO_H_
#define _PANEL_HX8394D_OTOTZ60_720P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config hx8394d_ototz60_720p_video_panel_data = {
	"qcom,mdss_dsi_hx8394d_ototz60_720p_video", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 0, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution hx8394d_ototz60_720p_video_panel_res = {
	720, 1280, 70, 70, 20, 0, 15, 12, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info hx8394d_ototz60_720p_video_color = {
	24, 0, 0xff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char hx8394d_ototz60_720p_video_on_cmd0[] = {
	0x04, 0x00, 0x39, 0xC0,
	0xB9, 0xFF, 0x83, 0x94,

};

static char hx8394d_ototz60_720p_video_on_cmd1[] = {
	0x03, 0x00, 0x39, 0xC0,
	0xBA, 0x72, 0x83, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd2[] = {
	0x10, 0x00, 0x39, 0xC0,
	0xB1, 0x6C, 0x12, 0x12,
	0x34, 0x04, 0x11, 0xF1,
	0x80, 0xFA, 0x54, 0x23,
	0x80, 0xC0, 0xD2, 0x58,

};

static char hx8394d_ototz60_720p_video_on_cmd3[] = {
	0x0C, 0x00, 0x39, 0xC0,
	0xB2, 0xC0, 0x64, 0x05,
	0x07, 0x32, 0x1C, 0x08,
	0x08, 0x1C, 0x4D, 0x00,

};

static char hx8394d_ototz60_720p_video_on_cmd4[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xBC, 0x07, 0xFF, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd5[] = {
	0x04, 0x00, 0x39, 0xC0,
	0xBF, 0x41, 0x0E, 0x01,

};

static char hx8394d_ototz60_720p_video_on_cmd6[] = {
	0x0D, 0x00, 0x39, 0xC0,
	0xB4, 0x00, 0xFF, 0x03,
	0x5A, 0x03, 0x5A, 0x03,
	0x5A, 0x01, 0x6A, 0x01,
	0x6A, 0xFF, 0xFF, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd7[] = {
	0x1F, 0x00, 0x39, 0xC0,
	0xD3, 0x00, 0x00, 0x00,
	0x40, 0x07, 0x10, 0x00,
	0x32, 0x10, 0x00, 0x00,
	0x00, 0x32, 0x15, 0x04,
	0x05, 0x04, 0x32, 0x15,
	0x28, 0x05, 0x27, 0x37,
	0x33, 0x00, 0x0B, 0x37,
	0x10, 0x07, 0x07, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd8[] = {
	0x2D, 0x00, 0x39, 0xC0,
	0xD5, 0x18, 0x18, 0x18,
	0x18, 0x18, 0x18, 0x18,
	0x18, 0x18, 0x18, 0x18,
	0x18, 0x18, 0x18, 0x25,
	0x24, 0x27, 0x26, 0x18,
	0x18, 0x05, 0x04, 0x01,
	0x00, 0x07, 0x06, 0x03,
	0x02, 0x43, 0x42, 0x47,
	0x46, 0x45, 0x44, 0x41,
	0x40, 0x21, 0x20, 0x23,
	0x22, 0x18, 0x18, 0x18,
	0x18, 0xFF, 0xFF, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd9[] = {
	0x2D, 0x00, 0x39, 0xC0,
	0xD6, 0x1A, 0x1A, 0x1B,
	0x1B, 0x0B, 0x0A, 0x09,
	0x08, 0x07, 0x06, 0x05,
	0x04, 0x03, 0x02, 0x01,
	0x00, 0x21, 0x20, 0x58,
	0x58, 0x27, 0x26, 0x18,
	0x18, 0x18, 0x18, 0x18,
	0x18, 0x18, 0x18, 0x18,
	0x18, 0x18, 0x18, 0x18,
	0x18, 0x18, 0x18, 0x25,
	0x24, 0x18, 0x18, 0x18,
	0x18, 0xFF, 0xFF, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd10[] = {
	0x2B, 0x00, 0x39, 0xC0,
	0xE0, 0x00, 0x20, 0x05,
	0x20, 0x28, 0x3F, 0x12,
	0x3B, 0x06, 0x09, 0x0B,
	0x17, 0x0E, 0x11, 0x14,
	0x12, 0x13, 0x09, 0x17,
	0x1C, 0x1F, 0x00, 0x02,
	0x05, 0x20, 0x28, 0x3F,
	0x12, 0x3B, 0x06, 0x09,
	0x0B, 0x17, 0x0E, 0x11,
	0x14, 0x12, 0x13, 0x09,
	0x17, 0x1C, 0x1F, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd11[] = {
	0x02, 0x00, 0x39, 0xC0,
	0xCC, 0x09, 0xFF, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd12[] = {
	0x03, 0x00, 0x39, 0xC0,
	0xB6, 0x3E, 0x3E, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd13[] = {
	0x03, 0x00, 0x39, 0xC0,
	0xC0, 0x30, 0x14, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd14[] = {
	0x05, 0x00, 0x39, 0xC0,
	0xC7, 0x00, 0xC0, 0x40,
	0xC0, 0xFF, 0xFF, 0xFF,
};

static char hx8394d_ototz60_720p_video_on_cmd15[] = {
	0x11, 0x00, 0x05, 0x80
};

static char hx8394d_ototz60_720p_video_on_cmd16[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd hx8394d_ototz60_720p_video_on_command[] = {
	{0x8, hx8394d_ototz60_720p_video_on_cmd0, 0x00},
	{0x8, hx8394d_ototz60_720p_video_on_cmd1, 0x00},
	{0x14, hx8394d_ototz60_720p_video_on_cmd2, 0x00},
	{0x10, hx8394d_ototz60_720p_video_on_cmd3, 0x00},
	{0x8, hx8394d_ototz60_720p_video_on_cmd4, 0x00},
	{0x8, hx8394d_ototz60_720p_video_on_cmd5, 0x00},
	{0x14, hx8394d_ototz60_720p_video_on_cmd6, 0x00},
	{0x24, hx8394d_ototz60_720p_video_on_cmd7, 0x00},
	{0x34, hx8394d_ototz60_720p_video_on_cmd8, 0x00},
	{0x34, hx8394d_ototz60_720p_video_on_cmd9, 0x00},
	{0x30, hx8394d_ototz60_720p_video_on_cmd10, 0x00},
	{0x8, hx8394d_ototz60_720p_video_on_cmd11, 0x00},
	{0x8, hx8394d_ototz60_720p_video_on_cmd12, 0x00},
	{0x8, hx8394d_ototz60_720p_video_on_cmd13, 0x00},
	{0xc, hx8394d_ototz60_720p_video_on_cmd14, 0x00},
	{0x4, hx8394d_ototz60_720p_video_on_cmd15, 0x78},
	{0x4, hx8394d_ototz60_720p_video_on_cmd16, 0x14}
};

#define HX8394D_OTOTZ60_720P_VIDEO_ON_COMMAND 17

/*---------------------------------------------------------------------------*/
/* Get LCD ID ----------    start   ---------------------------------------- */
/*---------------------------------------------------------------------------*/
static char hx8394f_720p_video_otot__read_id_cmd0[4] = { 0xDA, 0x00, 0x06, 0xA0 };
static char hx8394f_720p_video_otot__read_id_cmd1[4] = { 0xDB, 0x00, 0x06, 0xA0 };
static char hx8394f_720p_video_otot__read_id_cmd2[4] = { 0xDC, 0x00, 0x06, 0xA0 };

static char hx8394f_720p_video_otot__set_readmax_cmd[4] = { 0x04, 0x00, 0x37, 0x00 }; //read 4 bytes every time

static struct mipi_dsi_cmd hx8394f_720p_video_otot__read_id_cmd_s[] = {
	{sizeof(hx8394f_720p_video_otot__read_id_cmd0), hx8394f_720p_video_otot__read_id_cmd0, 0x00},
	{sizeof(hx8394f_720p_video_otot__read_id_cmd1), hx8394f_720p_video_otot__read_id_cmd1, 0x00},
	{sizeof(hx8394f_720p_video_otot__read_id_cmd2), hx8394f_720p_video_otot__read_id_cmd2, 0x00}
};
static struct mipi_dsi_cmd hx8394f_720p_video_otot__set_readmax_cmd_s =
	{sizeof(hx8394f_720p_video_otot__set_readmax_cmd), hx8394f_720p_video_otot__set_readmax_cmd};

//0xa8314b9 0xa942add 0xa0f70f7 :  data <<= 8; data |= data>>(32 -  signature_num *8); => data = 0x83940f
#define hx8394f_720p_video_otot__SIGNATURE_NUM  2  
#define hx8394f_720p_video_otot__SIGNATURE	0x83940D

static struct mipi_dsi_get_id get_hx8394f_otot_id = {
	.id_register_num	= 3, // <0xDA 0x83> <0xDB 0x94> <0xDC 0x0F>
	.signature_num		= hx8394f_720p_video_otot__SIGNATURE_NUM,
	.signature			= hx8394f_720p_video_otot__SIGNATURE,
	.mask				= 0xFF,
	.read_panel_id_cmds = hx8394f_720p_video_otot__read_id_cmd_s,
	.set_read_max_cmds	= &hx8394f_720p_video_otot__set_readmax_cmd,
};

/*---------------------------------------------------------------------------*/
/* Get LCD ID ----------    end ---------------------------------------------*/
/*---------------------------------------------------------------------------*/

static char hx8394d_ototz60_720p_videooff_cmd0[] = {
	0x28, 0x00, 0x05, 0x80
};

static char hx8394d_ototz60_720p_videooff_cmd1[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd hx8394d_ototz60_720p_video_off_command[] = {
	{0x4, hx8394d_ototz60_720p_videooff_cmd0, 0x32},
	{0x4, hx8394d_ototz60_720p_videooff_cmd1, 0x78}
};

#define HX8394D_OTOTZ60_720P_VIDEO_OFF_COMMAND 2


static struct command_state hx8394d_ototz60_720p_video_state = {
	0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info hx8394d_ototz60_720p_video_command_panel = {
	1, 1, 1, 0, 0, 0x2c, 0, 0, 0, 1, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info hx8394d_ototz60_720p_video_video_panel = {
	1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration hx8394d_ototz60_720p_video_lane_config = {
	3, 0, 1, 1, 1, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t hx8394d_ototz60_720p_video_timings[] = {
	0x96, 0x22, 0x18, 0x00, 0x4A, 0x4C, 0x1C, 0x26, 0x1A, 0x03, 0x04, 0x00
};

static struct panel_timing hx8394d_ototz60_720p_video_timing_info = {
	0, 4, 0x04, 0x30
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence hx8394d_ototz60_720p_video_reset_seq = {
	{1, 0, 1, }, {20, 20, 50, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight hx8394d_ototz60_720p_video_backlight = {
	1, 1, 255, 1, 0, "PMIC_8941"
};

#endif /*_PANEL_HX8394D_OTOTZ60_720P_VIDEO_H_*/
